### ISSUE TITLE
Error when running `make dockerprod`

### ISSUE THREAD

**Issue by decaffeinatedio** [readthedocs/ethical-ad-server#426]
Hi, 

Cool project! I've been able to get a local version up and running (on a pretty vanilla 21.04 box) by executing a few commands in sequence:

- `make dockerbuild`
- `make dockershell` then running a migration and superuser creation
- `make dockerserve`

Now I want to see if I can get it running in a cloud environment. However, I am running into several (stubborn) build issues with `make dockerprod`. 

First, I encountered as issue related to Alpine and the cryptography package, which I could resolve by adding `ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1` into `docker-compose/production/django/Dockerfile`. 

But now I'm running into an error during the the `RUN npm install` step that I can't seem to overcome: 

```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-clone-3208764b/node_modules/node-sass
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node scripts/build.js
npm ERR! npm ERR! Building: /usr/bin/node /root/.npm/_cacache/tmp/git-clone-3208764b/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp verb cli [
npm ERR! npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! npm ERR! gyp verb cli   '/root/.npm/_cacache/tmp/git-clone-3208764b/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! npm ERR! gyp verb cli   'rebuild',
npm ERR! npm ERR! gyp verb cli   '--verbose',
npm ERR! npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_library='
npm ERR! npm ERR! gyp verb cli ]
npm ERR! npm ERR! gyp info using node-gyp@3.8.0
npm ERR! npm ERR! gyp info using node@14.17.4 | linux | x64
npm ERR! npm ERR! gyp verb command rebuild []
npm ERR! npm ERR! gyp verb command clean []
npm ERR! npm ERR! gyp verb clean removing "build" directory
npm ERR! npm ERR! gyp verb command configure []
npm ERR! npm ERR! gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
npm ERR! npm ERR! gyp verb `which` succeeded /usr/bin/python3 /usr/bin/python3
npm ERR! npm ERR! gyp ERR! configure error 
npm ERR! npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack                       ^
npm ERR! npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! npm ERR! gyp ERR! stack 
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:12)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! npm ERR! gyp ERR! System Linux 5.11.0-7620-generic
npm ERR! npm ERR! gyp ERR! command "/usr/bin/node" "/root/.npm/_cacache/tmp/git-clone-3208764b/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! npm ERR! gyp ERR! cwd /root/.npm/_cacache/tmp/git-clone-3208764b/node_modules/node-sass
npm ERR! npm ERR! gyp ERR! node -v v14.17.4
npm ERR! npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! npm ERR! gyp ERR! not ok 
npm ERR! npm ERR! Build failed with error code: 1
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2021-08-03T02_48_09_697Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-03T02_48_10_380Z-debug.log
```

Anything I might be missing as a prereq in my build setup? Is there a better way to jump straight to testing in a self-hosted remote? 

Thank you!

**Comment by ericholscher** [comment]
@decaffeinatedio Thanks for opening an issue. We aren't currently deploying the code with docker anymore, so the `make dockerprod` might not be the best way to handle that moving forward. We don't have a lot of time to support custom installs, so I don't know if we have an obvious path forward for adding support for a more automated deployment option.

**Comment by decaffeinatedio** [comment]
@ericholscher thanks for the quick response! I’ll try to tinker with the ad server as a “bare metal” Django app and see if I can make some progress on deployment.
